// Drug reference data sourced directly from Barash Clinical Anesthesia, 9th Edition
// Chapters: 19 (IV Anesthetics), 20 (Opioids), 21 (NMB), 22 (Local Anesthetics), 13 (Cardiovascular Pharm)

export const BARASH_CATEGORIES = [
  { id: 'all',         label: 'All',                icon: '💊' },
  { id: 'induction',   label: 'Induction Agents',   icon: '💉' },
  { id: 'benzo',       label: 'Benzodiazepines',    icon: '😴' },
  { id: 'opioid',      label: 'Opioids',            icon: '🩺' },
  { id: 'ndmr',        label: 'NMB — Non-dep.',     icon: '💪' },
  { id: 'dmr',         label: 'NMB — Depol.',       icon: '⚡' },
  { id: 'reversal',    label: 'Reversal Agents',    icon: '🔄' },
  { id: 'local',       label: 'Local Anesthetics',  icon: '📍' },
];

// Source: Barash Clinical Anesthesia, 9th Edition
// Each entry includes exact quotes/data from the text where possible

export const BARASH_DRUGS = [

  // ── INDUCTION AGENTS — Ch.19 ─────────────────────────────────────────────
  {
    id: 'b_propofol_ind',
    name: 'Propofol',
    category: 'induction',
    indication: 'Induction of General Anesthesia',
    concentration: '1% (10 mg/mL)',
    doseRanges: [
      { population: 'Standard adult',       dose: '1.0–2.5 mg/kg IV',     note: 'Loss of consciousness at ~3 mcg/mL blood concentration' },
      { population: 'Elderly',              dose: 'Reduce 30–50%',        note: 'Decreased cardiac output and clearance → increased sensitivity' },
      { population: 'Morbidly obese',       dose: 'Use lean body weight',  note: 'Lean body weight for dose calculation per Barash' },
      { population: 'Cardiac disease',      dose: 'Careful titration',     note: 'Exaggerated hemodynamic response expected' },
    ],
    mechanism: 'GABA-A receptor agonist — enhances GABAergic inhibitory pathways',
    keyPoints: [
      'Causes significant decrease in SVR, stroke volume, and cardiac output',
      'Respiratory depressant and potent bronchodilator',
      'Antiemetic properties at low blood concentrations (350 ng/mL)',
      'Safe in malignant hyperthermia — not a trigger',
      'PRIS risk: avoid >4 mg/kg/h for >48h',
    ],
    sideEffects: 'Hypotension, apnea, pain on injection (60–70%), PRIS with prolonged infusion',
    contraindications: 'Propofol allergy; caution in egg/soy allergy (lipid emulsion)',
    color: '#6366f1',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 pp.1478–1480",
  },
  {
    id: 'b_propofol_sed',
    name: 'Propofol',
    category: 'induction',
    indication: 'Sedation / MAC (infusion)',
    concentration: '1% (10 mg/mL)',
    doseRanges: [
      { population: 'Standard sedation',    dose: '25–75 mcg/kg/min',     note: 'Titrate to effect; apnea avoided with careful rate adjustment' },
      { population: 'TIVA maintenance',     dose: '50–150 mcg/kg/min',    note: 'Combined with opioid (e.g. remifentanil) for TIVA' },
    ],
    mechanism: 'GABA-A receptor agonist',
    keyPoints: [
      'Context-sensitive half-time <40 min for infusions up to 8 hours',
      'For ICU sedation — PRIS risk at high doses/prolonged duration',
      'Used in rigid bronchoscopy, office-based anesthesia',
    ],
    sideEffects: 'Respiratory depression, hypotension, PRIS (rare but fatal)',
    contraindications: 'Triglyceride disorders; PRIS risk in ICU',
    color: '#6366f1',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 p.1479",
  },
  {
    id: 'b_etomidate',
    name: 'Etomidate',
    category: 'induction',
    indication: 'Hemodynamically Stable Induction',
    concentration: '2 mg/mL',
    doseRanges: [
      { population: 'Standard adult',       dose: '0.2–0.3 mg/kg IV',     note: 'Induction dose — Table 19-4 Barash' },
      { population: 'Elderly / cardiac',    dose: '0.1–0.2 mg/kg IV',     note: 'Reduced dose given prolonged half-life in elderly' },
    ],
    mechanism: 'GABA-A receptor agonist — hemodynamically stable',
    keyPoints: [
      'Minimal effect on MAP, PA pressure, stroke volume, SVR',
      'Adrenocortical suppression after single dose (6–8h)',
      'Used for cardiac, trauma, hypovolemic patients',
      'Increases SSEP amplitude — avoid in neuro cases requiring SSEP monitoring',
      'Proconvulsant on EEG — caution in neurosurgery',
    ],
    sideEffects: 'Adrenal suppression, myoclonus, PONV, pain on injection (propylene glycol)',
    contraindications: 'Sepsis (relative — adrenal suppression concern), avoid repeated doses',
    color: '#10b981',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 pp.1481–1483, Table 19-4",
  },
  {
    id: 'b_ketamine',
    name: 'Ketamine',
    category: 'induction',
    indication: 'Dissociative Induction / Analgesia',
    concentration: '10 mg/mL or 50 mg/mL',
    doseRanges: [
      { population: 'Induction (IV)',        dose: '0.5–2 mg/kg IV',       note: 'Onset 30–60 sec, duration 10–15 min — Table 19-5 Barash' },
      { population: 'Induction (IM)',        dose: '4–6 mg/kg IM',         note: '93% bioavailability IM; delayed onset' },
      { population: 'Analgesia / sub-diss.', dose: '0.1–0.5 mg/kg IV',    note: 'Sub-dissociative dose for analgesia; NMDA antagonism' },
    ],
    mechanism: 'NMDA receptor antagonist — dissociative anesthesia',
    keyPoints: [
      'Maintains airway reflexes, BP, and HR — ideal for hemodynamic instability',
      'Bronchodilator — preferred in bronchospasm / asthma',
      'S(+) enantiomer 3–4× more potent, shorter duration',
      'Prevents wind-up (spinal sensitization) at low doses',
      'Emergence delirium — co-administer midazolam to reduce',
    ],
    sideEffects: 'Emergence delirium, hallucinations, nystagmus, hypersalivation, increased ICP/IOP',
    contraindications: 'Raised ICP, ischemic heart disease, severe hypertension (relative)',
    color: '#f59e0b',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 pp.1483–1485, Table 19-5",
  },
  {
    id: 'b_thiopental',
    name: 'Thiopental (Pentothal)',
    category: 'induction',
    indication: 'Induction / Neuro Protection',
    concentration: '2.5% (25 mg/mL)',
    doseRanges: [
      { population: 'Standard adult',       dose: '2.5–5 mg/kg IV',       note: 'Loss of consciousness in 15–30 sec; deeper in 30–40 sec' },
      { population: 'Elderly',              dose: 'Reduced — smaller Vd', note: 'Decreased Vd and slower redistribution' },
      { population: 'Obese',               dose: 'Use lean body weight',  note: 'Lower per-kg requirement in obesity' },
      { population: 'Premedicated',         dose: 'May reduce by 50%',    note: 'Premedication can halve the requirement' },
    ],
    mechanism: 'GABA-A receptor agonist; NMDA antagonism at cortical/brainstem level',
    keyPoints: [
      'Rapid onset from bolus, terminated by redistribution',
      'Long context-sensitive half-time — NOT suitable for infusion',
      'Neuroprotective: decreases CMRO2, ICP, CBF',
      'Anticonvulsant — used for status epilepticus and burst suppression',
      'CONTRAINDICATED in porphyria',
    ],
    sideEffects: 'Hypotension, cardiac depression, respiratory depression, histamine release',
    contraindications: 'Porphyria (absolute); severe cardiovascular disease, hypovolemia',
    color: '#8b5cf6',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 pp.1507–1508, Table 19-11",
  },
  {
    id: 'b_dexmed',
    name: 'Dexmedetomidine',
    category: 'induction',
    indication: 'Procedural Sedation / Adjunct',
    concentration: '200 mcg/2 mL (100 mcg/mL)',
    doseRanges: [
      { population: 'Loading dose',         dose: '0.5–1 mcg/kg over 10 min', note: 'IV loading infusion; adjust for hemodynamics' },
      { population: 'Maintenance',          dose: '0.2–0.7 mcg/kg/h',    note: 'ICU sedation and procedural sedation' },
    ],
    mechanism: 'Selective α2-adrenergic agonist — sedation without respiratory depression',
    keyPoints: [
      'Unique: sedation with LIMITED respiratory depression',
      'Analgesia-sparing properties',
      'ICU sedation in mechanically ventilated patients',
      'Bradycardia and hypotension — common side effects',
      'Adjunct to general anesthesia for MAC reduction',
    ],
    sideEffects: 'Bradycardia, hypotension, dry mouth',
    contraindications: 'Pre-existing bradycardia, heart block',
    color: '#0ea5e9',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 pp.1491–1497",
  },

  // ── BENZODIAZEPINES — Ch.19 ──────────────────────────────────────────────
  {
    id: 'b_midazolam_premed',
    name: 'Midazolam',
    category: 'benzo',
    indication: 'Premedication (Anxiolysis / Amnesia)',
    concentration: '1 mg/mL or 5 mg/mL',
    doseRanges: [
      { population: 'IV premedication',     dose: '0.02–0.04 mg/kg IV/IM', note: 'Table 19-10: anxiolysis + anterograde amnesia' },
      { population: 'Oral premedication',   dose: '0.4–0.8 mg/kg PO',      note: 'For pediatric patients' },
      { population: 'Elderly',              dose: 'Reduce by 50%',          note: 'Increased sensitivity; prolonged effect' },
    ],
    mechanism: 'GABA-A receptor positive allosteric modulator',
    keyPoints: [
      'Provides anxiolysis, anterograde amnesia, sedation',
      'Water-soluble at low pH (IV formulation) → less pain on injection vs diazepam',
      'Short-acting compared to diazepam (high hepatic clearance)',
      'Reversible with flumazenil',
      'Hemodynamically stable — minimal SVR decrease',
    ],
    sideEffects: 'Respiratory depression (especially with opioids), paradoxical excitation in elderly',
    contraindications: 'Respiratory compromise (relative)',
    color: '#06b6d4',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 pp.1498–1501, Table 19-10",
  },
  {
    id: 'b_midazolam_ind',
    name: 'Midazolam',
    category: 'benzo',
    indication: 'Induction supplement (Hypnosis)',
    concentration: '1 mg/mL or 5 mg/mL',
    doseRanges: [
      { population: 'Induction (IV)',        dose: '0.1–0.2 mg/kg IV',     note: 'Table 19-10: hypnosis/amnesia/sedation' },
      { population: 'Infusion (maintenance)', dose: '0.25–1 mcg/kg/min',   note: 'In conjunction with volatile anesthetics' },
    ],
    mechanism: 'GABA-A receptor positive allosteric modulator',
    keyPoints: [
      'Slower onset than propofol — not preferred sole induction agent',
      'Infusion for maintenance in combination with volatile agents',
    ],
    sideEffects: 'Respiratory depression, prolonged sedation in elderly/renal failure',
    contraindications: 'Acute narrow-angle glaucoma',
    color: '#06b6d4',
    ref: "Barash Clinical Anesthesia 9e, Ch.19 p.1501, Table 19-10",
  },

  // ── OPIOIDS — Ch.20 ────────────────────────────────────────────────────────
  {
    id: 'b_morphine',
    name: 'Morphine',
    category: 'opioid',
    indication: 'Analgesia (IV)',
    concentration: '10 mg/mL',
    doseRanges: [
      { population: 'Intraoperative bolus',  dose: '0.15–0.2 mg/kg IV',    note: 'Give at least 60 min before end of surgery (t½ke0 ~1.5h)' },
      { population: 'PACU titration',        dose: '2 mg IV q5–10 min',     note: 'Until VAS ≤30/100; then PCA' },
      { population: 'PCA',                   dose: '1 mg/dose, 5 min lockout, max 24 mg/4h', note: 'Standard PCA regimen from Barash Ch.20' },
    ],
    mechanism: 'Mu-opioid receptor (MOR) agonist',
    keyPoints: [
      't½ke0 for analgesia ~1.5h — slow onset; give early',
      'Active metabolite M6G accumulates in renal failure',
      '1–2h delay between peak plasma concentration and peak analgesic effect',
      'PONV common; opioid-induced hyperalgesia with chronic high doses',
      'Multimodal: combine with acetaminophen + NSAIDs (opioid-sparing)',
    ],
    sideEffects: 'Respiratory depression, PONV, pruritus, constipation, M6G accumulation in renal failure',
    contraindications: 'Renal failure (caution — M6G accumulation)',
    color: '#ec4899',
    ref: "Barash Clinical Anesthesia 9e, Ch.20 pp.1554, 1538",
  },
  {
    id: 'b_fentanyl',
    name: 'Fentanyl',
    category: 'opioid',
    indication: 'Intraoperative Analgesia',
    concentration: '50 mcg/mL',
    doseRanges: [
      { population: 'Intraoperative bolus',  dose: '1.5–3 mcg/kg IV',      note: 'Reduces volatile anesthetic/propofol requirements ~50%; t½ke0 10–20 min' },
      { population: 'Supplemental doses',    dose: '100–150 mcg IV prn',    note: 'Give 5–10 min before anticipated painful stimulus' },
      { population: 'Elderly',              dose: 'Reduce 30–50%',         note: 'Increased sensitivity' },
    ],
    mechanism: 'Mu-opioid receptor agonist — 100× more potent than morphine',
    keyPoints: [
      't½ke0 for analgesia 10–20 min; t½ke0 for respiratory depression 15 min',
      'Context-sensitive half-time increases rapidly with infusion duration',
      'Synergistic with propofol — reduces both drug requirements',
      'Administer 5–10 min before laryngoscopy/incision',
      'Accumulates with prolonged infusion — caution in long cases',
    ],
    sideEffects: 'Respiratory depression, chest wall rigidity (high doses), bradycardia',
    contraindications: 'Caution with MAOIs',
    color: '#ec4899',
    ref: "Barash Clinical Anesthesia 9e, Ch.20 pp.1554–1555",
  },
  {
    id: 'b_remifentanil',
    name: 'Remifentanil',
    category: 'opioid',
    indication: 'Intraoperative Infusion (TIVA / Fast-Track)',
    concentration: '20–50 mcg/mL (reconstituted)',
    doseRanges: [
      { population: 'Infusion (standard)',   dose: '0.05–0.5 mcg/kg/min',  note: 'Titrate to hemodynamic response; CP50 varies 50-fold between patients' },
      { population: 'If bolus needed',       dose: '0.5–1 mcg/kg slow IV', note: 'Give over 1–2 min only; causes severe bradycardia/hypotension if fast' },
      { population: 'Optimal TIVA (with propofol)', dose: 'Remifentanil ~4.8 ng/mL + Propofol ~2.5 mcg/mL', note: 'Shortest wake-up ~7 min at these TCI concentrations' },
    ],
    mechanism: 'Mu-opioid receptor agonist; metabolized by non-specific plasma esterases',
    keyPoints: [
      'Ultra-short context-sensitive half-time — INDEPENDENT of infusion duration (t½ ~3 min)',
      '100–200× more potent than morphine',
      'Between intubation and incision: reduce infusion 30–40% to avoid hypotension/bradycardia',
      'HIGH risk of opioid-induced hyperalgesia (OIH) post-op',
      'Start morphine 30–45 min before end of surgery OR single fentanyl 50 mcg at end',
    ],
    sideEffects: 'Severe bradycardia/hypotension (bolus), postoperative OIH and pain, no postop analgesia',
    contraindications: 'Not for IM/spinal use (formulation contains glycine)',
    color: '#ec4899',
    ref: "Barash Clinical Anesthesia 9e, Ch.20 pp.1558–1561",
  },
  {
    id: 'b_sufentanil',
    name: 'Sufentanil',
    category: 'opioid',
    indication: 'Intraoperative Analgesia / High-dose Cardiac',
    concentration: '50 mcg/mL',
    doseRanges: [
      { population: 'Balanced anesthesia',  dose: '0.25–1 mcg/kg IV',     note: '10× more potent than fentanyl; stable cardiac output' },
      { population: 'High-dose cardiac',    dose: '8–30 mcg/kg',           note: 'Used with N2O for cardiac surgery — hemodynamic stability' },
    ],
    mechanism: 'Selective MOR agonist — highest therapeutic index of clinical opioids',
    keyPoints: [
      '10× more potent than fentanyl; 2× lipophilicity',
      'Stable hemodynamics and cardiac output',
      'Active metabolite desmethylsufentanil (10% activity, clinically negligible)',
      'Sublingual sufentanil PCA system available for postoperative pain',
    ],
    sideEffects: 'Respiratory depression, bradycardia, chest wall rigidity',
    contraindications: 'None absolute in appropriate doses',
    color: '#ec4899',
    ref: "Barash Clinical Anesthesia 9e, Ch.20 pp.1557–1558",
  },

  // ── NMB DEPOLARIZING — Ch.21 ─────────────────────────────────────────────
  {
    id: 'b_succinylcholine',
    name: 'Succinylcholine (Suxamethonium)',
    category: 'dmr',
    indication: 'RSI / Emergency Intubation',
    concentration: '20 mg/mL',
    doseRanges: [
      { population: 'Standard RSI (adult)',  dose: '1.0–1.5 mg/kg IV (TBW)', note: 'ED95 = 0.3 mg/kg; 1 mg/kg → DUR 25% of 10–12 min' },
      { population: 'RSI (obese)',           dose: 'Use ACTUAL body weight',   note: 'Barash: TBW for obese — unlike NDMRs which use IBW' },
      { population: 'Pediatric',             dose: '1.5–2 mg/kg IV (up to 3 mg/kg infants)', note: 'FDA black box: only for emergency airway in pediatrics' },
      { population: 'IM (no IV access)',     dose: '3–4 mg/kg IM',             note: 'Delayed onset; use when IV unavailable' },
    ],
    mechanism: 'Depolarizing NMB — mimics ACh, sustained depolarization → flaccid paralysis',
    keyPoints: [
      'Fastest onset (<60 sec) and shortest duration (5–10 min at 1 mg/kg) of any NMB',
      'Reference standard for RSI — alternative is rocuronium 1.2 mg/kg',
      'Diaphragm may recover before limb muscles — some breathing may resume in 5 min',
      'Phase II block with repeated large doses (≥10 × ED95)',
      'No reversal agent — wait for spontaneous recovery or plasma cholinesterase metabolism',
    ],
    sideEffects: 'Bradycardia (especially children), fasciculations, myalgias (50–60%), K⁺ ↑0.5 mEq/L, IOP↑15 mmHg, ICP↑',
    contraindications: 'MH history, burns >24h, crush injury, denervation, DMD/myopathy, hyperkalemia, prolonged immobilization, penetrating eye with inadequate anesthesia',
    isHighAlert: true,
    color: '#ef4444',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1609–1613",
  },

  // ── NMB NON-DEPOLARIZING — Ch.21 ─────────────────────────────────────────
  {
    id: 'b_rocuronium',
    name: 'Rocuronium',
    category: 'ndmr',
    indication: 'Intubation / Maintenance (Intermediate)',
    concentration: '10 mg/mL',
    doseRanges: [
      { population: 'Standard intubation',   dose: '0.6 mg/kg IV (IBW)',    note: 'Table 21-1: onset 1.5–3 min, clinical duration 30–70 min' },
      { population: 'RSI dose',              dose: '0.9–1.2 mg/kg IV (TBW)', note: 'Rapid paralysis in ~90 sec; comparable to succinylcholine; requires sugammadex 16 mg/kg to reverse immediately' },
      { population: 'Maintenance',           dose: '10% of intubating dose', note: 'When T1 returns to 25%; guided by TOF monitoring' },
      { population: 'Infusion',              dose: '5–12 mcg/kg/min',        note: 'Table 21-1 Barash' },
    ],
    mechanism: 'Aminosteroid NDMR — competitive ACh antagonist at nicotinic receptor α-subunit',
    keyPoints: [
      'ED95 = 0.3 mg/kg; low potency enables fast onset',
      'Women: ED95 is 15–25% lower than men',
      'Elderly: significantly longer duration',
      'Laparoscopy: 25% longer duration (reduced hepatic blood flow)',
      'Highest anaphylaxis rate of NDMRs (along with succinylcholine)',
      'Cleared by bile unchanged; 30% renal excretion',
      'Full reversal by sugammadex at any depth',
    ],
    sideEffects: 'Anaphylaxis (IgE-mediated, especially in hairdressers), mild cardiac muscarinic block',
    contraindications: 'Known allergy; caution in hepatic failure (prolonged duration)',
    color: '#34d399',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1621, Table 21-1",
  },
  {
    id: 'b_vecuronium',
    name: 'Vecuronium',
    category: 'ndmr',
    indication: 'Intubation / Maintenance (Intermediate)',
    concentration: '1 mg/mL (reconstituted)',
    doseRanges: [
      { population: 'Intubation',            dose: '0.1 mg/kg IV (IBW)',    note: 'Table 21-1: onset 3–4 min, clinical duration 25–50 min' },
      { population: 'Maintenance',           dose: '10% of intubating dose', note: 'Monitor with TOF' },
      { population: 'Infusion',              dose: '1–2 mcg/kg/min',         note: 'Table 21-1 Barash' },
    ],
    mechanism: 'Aminosteroid NDMR — competitive ACh antagonist',
    keyPoints: [
      'ED95 = 0.05 mg/kg (more potent than rocuronium)',
      'Active metabolite 3-desacetylvecuronium (50–70% potency) — accumulates in hepatic/renal failure',
      'No vagolytic effect — no tachycardia',
      'Precipitates with thiopental — give separately',
      'Prolonged duration in diabetic patients (case reports)',
      'Myopathy with prolonged ICU use + steroids',
    ],
    sideEffects: 'Prolonged block in hepatic failure, myopathy (ICU)',
    contraindications: 'Significant hepatic failure (accumulation of active metabolite)',
    color: '#34d399',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1621, Table 21-1",
  },
  {
    id: 'b_cisatracurium',
    name: 'Cisatracurium',
    category: 'ndmr',
    indication: 'Intubation / Maintenance (Intermediate)',
    concentration: '2 mg/mL',
    doseRanges: [
      { population: 'Intubation',            dose: '0.15–0.2 mg/kg IV',    note: 'Table 21-1: onset ~3–5 min (slower due to high potency), clinical duration 45–60 min' },
      { population: 'Maintenance',           dose: '10% of intubating dose', note: 'Monitor with TOF' },
      { population: 'Infusion',              dose: 'Not listed in Table 21-1', note: 'Can be used; titrate to TOF' },
    ],
    mechanism: 'Benzylisoquinolinium NDMR — Hofmann elimination (pH/temp dependent)',
    keyPoints: [
      'ED95 = 0.05 mg/kg (most potent of benzylisoquinolinium compounds)',
      'Hofmann elimination — organ-independent metabolism',
      'NO histamine release (unlike atracurium)',
      'Lowest IgE-mediated anaphylaxis rate of all NDMRs',
      'Preferred in organ failure patients (renal + hepatic)',
    ],
    sideEffects: 'Laudanosine metabolite (CNS excitatory) — not clinically significant at standard doses',
    contraindications: 'None absolute',
    color: '#34d399',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1622, Table 21-1",
  },
  {
    id: 'b_atracurium',
    name: 'Atracurium',
    category: 'ndmr',
    indication: 'Intubation / Maintenance (Intermediate)',
    concentration: '10 mg/mL',
    doseRanges: [
      { population: 'Intubation (2×ED95)',   dose: '0.5 mg/kg IV',          note: 'Table 21-1; onset 3–5 min at this dose' },
      { population: 'Maintenance',           dose: '10% of intubating dose', note: 'TOF guided' },
    ],
    mechanism: 'Benzylisoquinolinium NDMR — ester hydrolysis + Hofmann elimination',
    keyPoints: [
      'Hofmann elimination — organ-independent metabolism',
      'HISTAMINE RELEASE at intubating doses — may cause hypotension/tachycardia',
      'Increasing dose to speed onset → increased histamine release',
      'Preferred in renal and hepatic failure',
    ],
    sideEffects: 'Histamine release (hypotension, tachycardia, bronchospasm)',
    contraindications: 'Hypersensitivity; caution in atopy/asthma (histamine release)',
    color: '#34d399',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1621–1622, Table 21-1",
  },
  {
    id: 'b_pancuronium',
    name: 'Pancuronium',
    category: 'ndmr',
    indication: 'Long-Duration NMB (ICU/Cardiac Surgery)',
    concentration: '2 mg/mL',
    doseRanges: [
      { population: 'Intubation',            dose: '0.1 mg/kg IV (IBW)',    note: 'Table 21-1: onset 2–4 min, clinical duration 60–120 min' },
      { population: 'Maintenance',           dose: '10% of intubating dose', note: 'Infusion NOT recommended — accumulation' },
    ],
    mechanism: 'Aminosteroid NDMR — competitive ACh antagonist + vagolytic',
    keyPoints: [
      'LONG duration (60–120 min) — increased risk of residual block',
      'Vagolytic → TACHYCARDIA — avoid in tachycardia/ischemic disease',
      'Renal and hepatic elimination → prolonged in failure',
      'Active metabolites (3-OH-pancuronium, 17-OH-pancuronium) — prolong block',
      'Barash: "rarely used due to increased risk of residual neuromuscular blockade"',
    ],
    sideEffects: 'Tachycardia (vagolytic), significant accumulation/residual block',
    contraindications: 'Tachyarrhythmias, renal failure (significant prolongation)',
    color: '#34d399',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1620–1621, Table 21-1",
  },

  // ── REVERSAL AGENTS — Ch.21 ──────────────────────────────────────────────
  {
    id: 'b_neostigmine',
    name: 'Neostigmine',
    category: 'reversal',
    indication: 'Reversal of NDMR (Anticholinesterase)',
    concentration: '0.5 mg/mL or 2.5 mg/mL',
    doseRanges: [
      { population: 'Minimal block (TOF ratio ≥0.4)',   dose: '15–30 mcg/kg IV',     note: 'Barash p.1653: shallower block → lower dose' },
      { population: 'Shallow block (TOF ratio 0.4–<0.4, TOFC 4)', dose: '40–50 mcg/kg IV', note: 'Max effective dose; higher doses add no benefit' },
      { population: 'TOF ratio >0.6',                   dose: '10–20 mcg/kg IV',     note: 'Lowest effective dose at near-recovery' },
    ],
    mechanism: 'Acetylcholinesterase inhibitor → increases ACh at NMJ → competitive reversal',
    keyPoints: [
      'CEILING EFFECT — max dose 50 mcg/kg; higher doses provide no additional reversal',
      'Only effective when block is MINIMAL (TOFC 4, no fade) or SHALLOW (TOFC 4 with fade)',
      'NOT recommended for moderate block (TOFC 1–3) — cannot reliably achieve TOF ratio ≥0.9',
      'Give atropine (7–15 mcg/kg) or glycopyrrolate (10 mcg/kg) with every dose',
      'Peak effect ~10 min — administer ≥10–15 min before planned extubation',
      'Inhibits pseudocholinesterase — avoid if succinylcholine may be needed again',
    ],
    sideEffects: 'Bradycardia, bronchospasm, hypersalivation, PONV (if no anticholinergic given)',
    contraindications: 'Moderate/deep NMB (ineffective); immediately after succinylcholine',
    color: '#a78bfa',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1650–1653, Table 21-8",
  },
  {
    id: 'b_sugammadex_mod',
    name: 'Sugammadex',
    category: 'reversal',
    indication: 'Reversal — Moderate Block (TOFC ≥2)',
    concentration: '100 mg/mL (200 mg/2 mL)',
    doseRanges: [
      { population: 'Moderate block (TOFC ≥2)',          dose: '2 mg/kg IV (TBW)',    note: 'TOF ratio ≥0.9 in 2–4 min; elderly may take longer' },
      { population: 'Deep block (TOFC 0, PTC 1–2)',      dose: '4 mg/kg IV (TBW)',    note: 'From Barash p.1659' },
      { population: 'Immediate reversal (RSI roc 1.2 mg/kg)', dose: '16 mg/kg IV (TBW)', note: 'CICV rescue: give within 3 min of rocuronium' },
      { population: 'Near-recovery (TOFC 4, no fade)',   dose: '0.5–1 mg/kg',         note: 'Low-dose; risk of recurrence if < minimal block — use TOF monitoring' },
    ],
    mechanism: 'Modified γ-cyclodextrin — encapsulates rocuronium/vecuronium in plasma, shifting drug away from NMJ',
    keyPoints: [
      'Rocuronium binding 3× tighter than vecuronium',
      'NOT effective for succinylcholine, atracurium, cisatracurium, mivacurium',
      'Dose based on ACTUAL body weight (not IBW) — including obese',
      'Renal excretion; avoid in severe renal failure (drug/complex not excreted)',
      'Wait ≥24h before re-dosing aminosteroid NMB after sugammadex',
      'Minimal hemodynamic side effects; may slightly prolong aPTT (transient)',
      'FDA: not always successful — use quantitative monitoring to confirm reversal',
    ],
    sideEffects: 'Rare hypersensitivity/anaphylaxis (cardiovascular collapse treated with epinephrine); oral contraceptive interaction (treat as missed dose)',
    contraindications: 'Severe renal failure (relative); benzylisoquinolinium NMB block (ineffective)',
    color: '#a78bfa',
    ref: "Barash Clinical Anesthesia 9e, Ch.21 pp.1658–1661",
  },

  // ── LOCAL ANESTHETICS — Ch.22 ────────────────────────────────────────────
  {
    id: 'b_lidocaine',
    name: 'Lidocaine',
    category: 'local',
    indication: 'Regional / Infiltration / IV Antiarrhythmic',
    concentration: '1% (10 mg/mL) or 2% (20 mg/mL)',
    doseRanges: [
      { population: 'Infiltration (plain)',    dose: 'Max 4.5 mg/kg',          note: 'Table 22-9; absolute max ~300 mg' },
      { population: 'Infiltration (+epi)',     dose: 'Max 7 mg/kg',             note: 'Table 22-9; absolute max ~500 mg' },
      { population: 'IV antiarrhythmic bolus', dose: '1–1.5 mg/kg IV',         note: 'Table 22-11: toxic CNS effects begin >5 mcg/mL plasma' },
      { population: 'IV (reduce propofol pain)', dose: '0.5–1 mg/kg IV',       note: 'Pre-injection; most effective method' },
    ],
    mechanism: 'Voltage-gated sodium channel blocker (intracellular binding)',
    keyPoints: [
      'Relative CNS toxicity potency = 1.0 (reference); CVS:CNS ratio = 7.1 (safest)',
      'Metabolized by liver — reduce dose in hepatic/cardiac failure',
      'CNS toxicity sequence: tinnitus → tongue numbness → seizures → coma → arrest',
      'Cardiovascular toxicity at much higher concentrations than CNS toxicity',
      'Fastest metabolism of amide local anesthetics',
    ],
    sideEffects: 'CNS toxicity (seizures), cardiovascular depression at high doses',
    contraindications: 'Allergy to amide local anesthetics (rare)',
    color: '#64748b',
    ref: "Barash Clinical Anesthesia 9e, Ch.22 pp.1703–1704, Tables 22-8, 22-9, 22-11",
  },
  {
    id: 'b_bupivacaine',
    name: 'Bupivacaine',
    category: 'local',
    indication: 'Regional / Spinal / Epidural',
    concentration: '0.25% (2.5 mg/mL) or 0.5% (5 mg/mL)',
    doseRanges: [
      { population: 'Infiltration / peripheral nerve (plain)', dose: 'Max 2.5 mg/kg', note: 'Table 22-9; absolute max ~150 mg' },
      { population: 'Infiltration (+epi)',     dose: 'Max 3 mg/kg',             note: 'Table 22-9' },
      { population: 'Spinal (hyperbaric)',     dose: '10–15 mg',                note: 'For spinal anesthesia; isobaric vs hyperbaric preparations' },
      { population: 'Epidural',               dose: '0.1–0.5% per technique',  note: 'Concentration and volume depend on block level required' },
    ],
    mechanism: 'Voltage-gated sodium channel blocker — long-acting due to high lipid solubility and protein binding',
    keyPoints: [
      'Relative CNS toxicity potency = 4.0 (most cardiotoxic amide)',
      'CVS:CNS ratio = 2.0 — NARROW safety margin (cardiovascular collapse before/with CNS toxicity)',
      'Highly protein-bound → long duration (2–8h for blocks)',
      'Treatment of LAST: IV lipid emulsion 20% (intralipid); AVOID epinephrine (worsens prognosis)',
      'Levobupivacaine (S-isomer) has 30–40% less CVS toxicity than racemic bupivacaine',
    ],
    sideEffects: 'MOST CARDIOTOXIC amide LA — ventricular arrhythmias, complete heart block, cardiovascular collapse',
    contraindications: 'IV regional anesthesia (Bier block) — ABSOLUTE contraindication',
    color: '#64748b',
    isHighAlert: true,
    ref: "Barash Clinical Anesthesia 9e, Ch.22 pp.1703–1708, Tables 22-8, 22-9",
  },
  {
    id: 'b_ropivacaine',
    name: 'Ropivacaine',
    category: 'local',
    indication: 'Regional / Epidural / Peripheral Nerve Blocks',
    concentration: '0.2% (2 mg/mL), 0.5% (5 mg/mL), or 0.75% (7.5 mg/mL)',
    doseRanges: [
      { population: 'Peripheral nerve block / infiltration', dose: 'Max 3–4 mg/kg', note: 'Table 22-9; pure S-enantiomer' },
      { population: 'Epidural (labour)',      dose: '0.1–0.2% epidural',     note: 'Low concentration for labour epidural analgesia' },
      { population: 'Epidural (surgical)',    dose: '0.5–0.75% epidural',    note: 'Higher concentration for surgical block' },
    ],
    mechanism: 'Voltage-gated sodium channel blocker — S(-) enantiomer only (less cardiodepressive than bupivacaine)',
    keyPoints: [
      'Relative CNS toxicity potency = 2.9 (same as levobupivacaine)',
      'CVS:CNS ratio = 2.0 — narrow safety margin but 30–40% LESS cardiotoxic than bupivacaine',
      'Propyl side chain → less cardiodepressive than butyl side chain of bupivacaine',
      'Motor block less pronounced than bupivacaine at same concentration',
      'Preferred for epidural labour analgesia and peripheral nerve blocks',
    ],
    sideEffects: 'Cardiotoxicity (less than bupivacaine), CNS toxicity',
    contraindications: 'IV regional anesthesia',
    color: '#64748b',
    ref: "Barash Clinical Anesthesia 9e, Ch.22 pp.1703–1708, Table 22-8",
  },
  {
    id: 'b_chloroprocaine',
    name: 'Chloroprocaine',
    category: 'local',
    indication: 'Epidural / Short-Duration Regional',
    concentration: '2% (20 mg/mL) or 3% (30 mg/mL)',
    doseRanges: [
      { population: 'Epidural (plain)',        dose: 'Max 11 mg/kg',           note: 'Very high max dose — rapidly hydrolyzed by plasma cholinesterase' },
      { population: 'Epidural (+epi)',         dose: 'Max 14 mg/kg',           note: 'Table 22-9 Barash' },
    ],
    mechanism: 'Aminoester LA — very rapid hydrolysis by plasma pseudocholinesterase',
    keyPoints: [
      'Shortest half-life (0.11h) → highest maximum dose',
      'Rapid onset and short duration — excellent for epidural top-up',
      'Safe in patients with pseudocholinesterase deficiency? — No; use amide alternatives',
      'Inhibits intrathecal opioid analgesia if used after spinal',
      'EDTA formulation can cause back pain (calcium chelation)',
    ],
    sideEffects: 'Back pain (EDTA formulation), may antagonize neuraxial opioids',
    contraindications: 'Intrathecal injection (risk of neurotoxicity with older formulations)',
    color: '#64748b',
    ref: "Barash Clinical Anesthesia 9e, Ch.22 Table 22-9",
  },
];
