// Barash Clinical Anesthesia 9e — calculator-compatible drug database
// Same structure as drugs.js so it can share DrugTable + calcDose utilities
// Sources: Ch.19 (IV Anesthetics), Ch.20 (Opioids), Ch.21 (NMB), Ch.22 (Local Anesthetics)

export const CATEGORIES = [
  { id: 'induction',   label: 'Induction',        icon: '💉' },
  { id: 'benzo',       label: 'Benzodiazepines',  icon: '😴' },
  { id: 'opioid',      label: 'Opioids',           icon: '🩺' },
  { id: 'ndmr',        label: 'NMB — Non-dep.',   icon: '💪' },
  { id: 'dmr',         label: 'NMB — Depol.',     icon: '⚡' },
  { id: 'reversal',    label: 'Reversal',          icon: '🔄' },
  { id: 'local',       label: 'Local Anesthetics', icon: '📍' },
];

export const DRUGS = [

  // ── INDUCTION — Ch.19 ──────────────────────────────────────────────────
  {
    id: 'b_propofol_ind',
    name: 'Propofol',
    indication: 'Induction',
    concentration: [{ label: '1% (10 mg/mL)', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'LBW',   // Barash: "lean body weight" for obese; standard adult use TBW
    category: 'induction',
    doses: {
      standard: { min: 1.0, max: 2.5 },
      elderly:  { min: 0.5, max: 1.5 },
      cardiac:  { min: 0.5, max: 1.5 },
    },
    notes: 'Loss of consciousness ~3 mcg/mL blood concentration. Barash: use LBW in morbidly obese. Exaggerated hemodynamic response in cardiac disease — titrate slowly.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 pp.1478–1480',
    contraindications: [],
    color: '#6366f1',
  },
  {
    id: 'b_propofol_sed',
    name: 'Propofol',
    indication: 'Sedation / TIVA maintenance',
    concentration: [{ label: '1% (10 mg/mL)', mgPerMl: 10 }],
    unit: 'mcg/kg/min',
    weightBasis: 'LBW',
    category: 'induction',
    doses: {
      standard: { min: 25,  max: 150 },
      elderly:  { min: 25,  max: 75  },
    },
    notes: 'Sedation: 25–75 mcg/kg/min. TIVA maintenance (with opioid): 50–150 mcg/kg/min. PRIS risk >4 mg/kg/h for >48h.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 p.1479',
    contraindications: [],
    color: '#6366f1',
    isInfusion: true,
  },
  {
    id: 'b_etomidate',
    name: 'Etomidate',
    indication: 'Induction',
    concentration: [{ label: '2 mg/mL', mgPerMl: 2 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 0.2, max: 0.3 },
      elderly:  { min: 0.1, max: 0.2 },
      cardiac:  { min: 0.2, max: 0.3 },
    },
    notes: 'Hemodynamically stable — preferred for cardiac, trauma, hypovolemia. Adrenocortical suppression after single dose (6–8h). Barash: Table 19-4.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 pp.1481–1483, Table 19-4',
    contraindications: ['adrenal_insufficiency'],
    color: '#10b981',
  },
  {
    id: 'b_ketamine_iv',
    name: 'Ketamine',
    indication: 'Induction (IV)',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }, { label: '50 mg/mL', mgPerMl: 50 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 0.5, max: 2.0 },
      elderly:  { min: 0.5, max: 1.0 },
    },
    notes: 'Onset 30–60 sec, duration 10–15 min. NMDA antagonist — dissociative anesthesia. S(+) enantiomer 3–4× more potent. Co-administer midazolam to reduce emergence delirium.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 pp.1483–1485, Table 19-5',
    contraindications: ['raised_icp'],
    color: '#f59e0b',
  },
  {
    id: 'b_ketamine_im',
    name: 'Ketamine',
    indication: 'Induction (IM)',
    concentration: [{ label: '50 mg/mL', mgPerMl: 50 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 4.0, max: 6.0 },
    },
    notes: 'IM bioavailability 93%. Delayed onset vs IV. Use when IV access unavailable.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 p.1484',
    contraindications: [],
    color: '#f59e0b',
  },
  {
    id: 'b_ketamine_analg',
    name: 'Ketamine',
    indication: 'Sub-dissociative analgesia',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 0.1, max: 0.5 },
    },
    notes: 'Low-dose NMDA antagonism for analgesia and opioid-sparing. Also used to prevent remifentanil-induced OIH (10–30 mg/h infusion per Barash Ch.20).',
    ref: 'Barash Clinical Anesthesia 9e, Ch.20 p.1538',
    contraindications: [],
    color: '#f59e0b',
  },
  {
    id: 'b_thiopental',
    name: 'Thiopental (Pentothal)',
    indication: 'Induction',
    concentration: [{ label: '2.5% (25 mg/mL)', mgPerMl: 25 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 2.5, max: 5.0 },
      elderly:  { min: 1.5, max: 3.0 },
    },
    notes: 'Rapid onset 15–30 sec, lasts ~1 min. Long context-sensitive half-time — NOT for infusion. Neuroprotective: reduces CMRO2, ICP, CBF. CONTRAINDICATED in porphyria.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 pp.1507–1508',
    contraindications: ['porphyria'],
    color: '#8b5cf6',
  },
  {
    id: 'b_dexmed_load',
    name: 'Dexmedetomidine',
    indication: 'Loading dose (procedural sedation)',
    concentration: [{ label: '4 mcg/mL (diluted)', mgPerMl: 0.004 }],
    unit: 'mcg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 0.5, max: 1.0 },
    },
    notes: 'α2-agonist. Infuse over 10 min to reduce hemodynamic side effects. Sedation WITHOUT respiratory depression — unique property.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 pp.1491–1497',
    contraindications: [],
    color: '#0ea5e9',
    isMcg: true,
  },
  {
    id: 'b_dexmed_maint',
    name: 'Dexmedetomidine',
    indication: 'Maintenance infusion',
    concentration: [{ label: '4 mcg/mL (diluted)', mgPerMl: 0.004 }],
    unit: 'mcg/kg/min',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 0.003, max: 0.012 },
      elderly:  { min: 0.003, max: 0.007 },
    },
    notes: '0.2–0.7 mcg/kg/h = 0.003–0.012 mcg/kg/min. ICU sedation and procedural sedation. Common side effects: bradycardia, hypotension.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 pp.1491–1497',
    contraindications: [],
    color: '#0ea5e9',
    isInfusion: true,
    isMcg: true,
  },

  // ── BENZODIAZEPINES — Ch.19 ─────────────────────────────────────────────
  {
    id: 'b_midazolam_premed',
    name: 'Midazolam',
    indication: 'Premedication (IV/IM)',
    concentration: [{ label: '1 mg/mL', mgPerMl: 1 }, { label: '5 mg/mL', mgPerMl: 5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'benzo',
    doses: {
      standard: { min: 0.02, max: 0.04 },
      elderly:  { min: 0.01, max: 0.02 },
    },
    maxDose: 5,
    notes: 'Table 19-10 Barash: 0.02–0.04 mg/kg IV/IM for anxiolysis + anterograde amnesia. Reduce 50% in elderly. Max 5 mg IV.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 Table 19-10 p.1501',
    contraindications: [],
    color: '#06b6d4',
  },
  {
    id: 'b_midazolam_ind',
    name: 'Midazolam',
    indication: 'Induction supplement',
    concentration: [{ label: '1 mg/mL', mgPerMl: 1 }, { label: '5 mg/mL', mgPerMl: 5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'benzo',
    doses: {
      standard: { min: 0.1, max: 0.2 },
      elderly:  { min: 0.05, max: 0.1 },
    },
    maxDose: 10,
    notes: 'Table 19-10 Barash: 0.1–0.2 mg/kg IV for hypnosis/amnesia/sedation at induction.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 Table 19-10 p.1501',
    contraindications: [],
    color: '#06b6d4',
  },
  {
    id: 'b_midazolam_inf',
    name: 'Midazolam',
    indication: 'Infusion (with volatile agent)',
    concentration: [{ label: '1 mg/mL', mgPerMl: 1 }],
    unit: 'mcg/kg/min',
    weightBasis: 'TBW',
    category: 'benzo',
    doses: {
      standard: { min: 0.25, max: 1.0 },
    },
    notes: 'Table 19-10 Barash: 0.25–1 mcg/kg/min infusion in conjunction with volatile anesthetics for hypnosis/amnesia.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.19 Table 19-10 p.1501',
    contraindications: [],
    color: '#06b6d4',
    isInfusion: true,
    isMcg: true,
  },

  // ── OPIOIDS — Ch.20 ─────────────────────────────────────────────────────
  {
    id: 'b_morphine',
    name: 'Morphine',
    indication: 'Intraoperative analgesia (IV)',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'opioid',
    doses: {
      standard: { min: 0.15, max: 0.2 },
      elderly:  { min: 0.05, max: 0.1 },
    },
    notes: 'Give ≥60 min before end of surgery (t½ke0 ~1.5h). Active metabolite M6G accumulates in renal failure. PACU titration: 2 mg IV q5–10 min until VAS ≤30. PCA: 1 mg/dose, 5 min lockout.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.20 pp.1554, 1538',
    contraindications: ['renal'],
    color: '#ec4899',
  },
  {
    id: 'b_fentanyl',
    name: 'Fentanyl',
    indication: 'Intraoperative analgesia',
    concentration: [{ label: '50 mcg/mL', mgPerMl: 0.05 }],
    unit: 'mcg/kg',
    weightBasis: 'TBW',
    category: 'opioid',
    doses: {
      standard: { min: 1.5, max: 3.0 },
      elderly:  { min: 0.75, max: 1.5 },
    },
    notes: 'Reduces volatile/propofol requirements ~50%. t½ke0 for analgesia 10–20 min. Give 5–10 min before laryngoscopy/incision. CSt½ increases rapidly with infusion duration.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.20 pp.1554–1555',
    contraindications: [],
    color: '#ec4899',
    isMcg: true,
  },
  {
    id: 'b_remifentanil',
    name: 'Remifentanil',
    indication: 'Intraoperative infusion (TIVA)',
    concentration: [{ label: '20 mcg/mL', mgPerMl: 0.02 }, { label: '50 mcg/mL', mgPerMl: 0.05 }],
    unit: 'mcg/kg/min',
    weightBasis: 'LBW',
    category: 'opioid',
    doses: {
      standard: { min: 0.05, max: 0.5 },
      elderly:  { min: 0.025, max: 0.25 },
    },
    notes: 'CSt½ ~3 min — independent of infusion duration. Optimal TIVA: ~4.8 ng/mL with propofol 2.5 mcg/mL (wake-up in ~7 min). Reduce 30–40% between intubation and incision. HIGH OIH risk — start morphine 30–45 min before end.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.20 pp.1558–1561',
    contraindications: [],
    color: '#ec4899',
    isInfusion: true,
    isMcg: true,
  },
  {
    id: 'b_sufentanil',
    name: 'Sufentanil',
    indication: 'Intraoperative analgesia',
    concentration: [{ label: '50 mcg/mL', mgPerMl: 0.05 }],
    unit: 'mcg/kg',
    weightBasis: 'TBW',
    category: 'opioid',
    doses: {
      standard: { min: 0.25, max: 1.0 },
      cardiac:  { min: 8.0,  max: 30.0 },
    },
    notes: '10× more potent than fentanyl. Highest therapeutic index of clinical opioids. Cardiac surgery: 8–30 mcg/kg high-dose technique.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.20 pp.1557–1558',
    contraindications: [],
    color: '#ec4899',
    isMcg: true,
  },

  // ── NMB DEPOLARIZING — Ch.21 ────────────────────────────────────────────
  {
    id: 'b_succinylcholine',
    name: 'Succinylcholine',
    indication: 'RSI / Emergency intubation',
    concentration: [{ label: '20 mg/mL', mgPerMl: 20 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'dmr',
    doses: {
      standard: { min: 1.0, max: 1.5 },
    },
    notes: 'Barash: use ACTUAL body weight in obese (unlike NDMRs). ED95 = 0.3 mg/kg. DUR 25% = 10–12 min at 1 mg/kg. Diaphragm may recover in ~5 min. No reversal agent.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 pp.1609–1613',
    contraindications: ['mh', 'burns', 'denervation', 'dmd', 'hyperkalemia'],
    color: '#ef4444',
    isHighAlert: true,
  },

  // ── NMB NON-DEPOLARIZING — Ch.21 ────────────────────────────────────────
  {
    id: 'b_rocuronium_int',
    name: 'Rocuronium',
    indication: 'Intubation (standard)',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.6, max: 0.6 },
    },
    notes: 'Table 21-1 Barash: intubating dose 0.6 mg/kg IBW. Onset 1.5–3 min. Clinical duration 30–70 min. Women: ED95 15–25% lower. Laparoscopy: 25% longer duration.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 Table 21-1 p.1618',
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'b_rocuronium_rsi',
    name: 'Rocuronium',
    indication: 'RSI dose',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.9, max: 1.2 },
    },
    notes: 'Barash: 0.9–1.2 mg/kg for rapid paralysis in ~90 sec. Cochrane 2015: no significant difference from succinylcholine at 1.2 mg/kg. Requires sugammadex 16 mg/kg for immediate reversal (CICV scenario).',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 pp.1612–1613',
    contraindications: [],
    color: '#ef4444',
    isHighAlert: true,
  },
  {
    id: 'b_rocuronium_maint',
    name: 'Rocuronium',
    indication: 'Maintenance dose',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.06, max: 0.12 },
    },
    notes: 'Table 21-1 Barash: 10% of intubating dose when T1 returns to 25%. Guided by TOF monitoring.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 Table 21-1 p.1618',
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'b_vecuronium',
    name: 'Vecuronium',
    indication: 'Intubation',
    concentration: [{ label: '1 mg/mL (reconstituted)', mgPerMl: 1 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.1, max: 0.1 },
    },
    notes: 'Table 21-1 Barash: 0.1 mg/kg. Onset 3–4 min. Duration 25–50 min. Active metabolite 3-desacetylvecuronium (50–70% potency) accumulates in hepatic failure. Precipitates with thiopental.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 Table 21-1 p.1618',
    contraindications: ['hepatic'],
    color: '#34d399',
  },
  {
    id: 'b_cisatracurium',
    name: 'Cisatracurium',
    indication: 'Intubation',
    concentration: [{ label: '2 mg/mL', mgPerMl: 2 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.15, max: 0.2 },
    },
    notes: 'Table 21-1 Barash: 0.15–0.2 mg/kg. Hofmann elimination — organ-independent. NO histamine release. Lowest IgE-mediated anaphylaxis rate. Preferred in organ failure.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 Table 21-1 p.1618',
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'b_atracurium',
    name: 'Atracurium',
    indication: 'Intubation',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.5, max: 0.5 },
    },
    notes: 'Table 21-1 Barash: 0.5 mg/kg (2×ED95). Onset 3–5 min. Hofmann elimination. HISTAMINE RELEASE at intubating doses — hypotension/tachycardia. Avoid rapid bolus.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 Table 21-1 p.1618',
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'b_pancuronium',
    name: 'Pancuronium',
    indication: 'Long-duration NMB',
    concentration: [{ label: '2 mg/mL', mgPerMl: 2 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.1, max: 0.1 },
    },
    notes: 'Table 21-1 Barash: 0.1 mg/kg. Duration 60–120 min. Vagolytic → tachycardia. Significant accumulation in renal/hepatic failure. Barash: "rarely used due to increased risk of residual block."',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 Table 21-1 p.1618',
    contraindications: ['renal', 'tachycardia'],
    color: '#34d399',
  },

  // ── REVERSAL — Ch.21 ────────────────────────────────────────────────────
  {
    id: 'b_neostigmine_min',
    name: 'Neostigmine',
    indication: 'Reversal — minimal block (TOF ratio ≥0.4)',
    concentration: [{ label: '0.5 mg/mL', mgPerMl: 0.5 }, { label: '2.5 mg/mL', mgPerMl: 2.5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 0.015, max: 0.03 },
    },
    maxDose: 5,
    notes: 'Barash p.1653: minimal block → 15–30 mcg/kg. Must co-administer glycopyrrolate 10 mcg/kg or atropine. Peak effect ~10 min — give ≥10–15 min before extubation. CEILING at 50 mcg/kg.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 p.1653',
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'b_neostigmine_sha',
    name: 'Neostigmine',
    indication: 'Reversal — shallow block (TOFC 4 with fade)',
    concentration: [{ label: '0.5 mg/mL', mgPerMl: 0.5 }, { label: '2.5 mg/mL', mgPerMl: 2.5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 0.04, max: 0.05 },
    },
    maxDose: 5,
    notes: 'Barash p.1653: shallow block → 40–50 mcg/kg. Max effective dose. Higher doses provide NO additional reversal (ceiling effect). NOT recommended for moderate block (TOFC 1–3).',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 p.1653',
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'b_sugammadex_mod',
    name: 'Sugammadex',
    indication: 'Reversal — moderate block (TOFC ≥2)',
    concentration: [{ label: '100 mg/mL', mgPerMl: 100 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 2.0, max: 2.0 },
    },
    notes: 'Barash p.1659: TOF ratio ≥0.9 in 2–4 min. Dose based on ACTUAL body weight (not IBW). Rocuronium/vecuronium only — ineffective for succinylcholine/benzylisoquinolinium NMB.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 pp.1658–1661',
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'b_sugammadex_deep',
    name: 'Sugammadex',
    indication: 'Reversal — deep block (TOFC 0, PTC 1–2)',
    concentration: [{ label: '100 mg/mL', mgPerMl: 100 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 4.0, max: 4.0 },
    },
    notes: 'Barash p.1659: 4 mg/kg for TOFC 0 with PTC 1–2. Renal failure: reversal time slightly prolonged (3.1 min vs 1.9 min normal). Mild hypothermia also prolongs reversal.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 pp.1658–1661',
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'b_sugammadex_imm',
    name: 'Sugammadex',
    indication: 'Immediate reversal — RSI rocuronium (CICV)',
    concentration: [{ label: '100 mg/mL', mgPerMl: 100 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 16.0, max: 16.0 },
    },
    notes: 'Barash p.1659: 16 mg/kg for "cannot intubate cannot oxygenate" after RSI rocuronium 1.2 mg/kg. Give within 3 min of rocuronium. Wait ≥24h before re-administering aminosteroid NMB.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.21 p.1659',
    contraindications: [],
    color: '#ef4444',
    isHighAlert: true,
  },

  // ── LOCAL ANESTHETICS — Ch.22 ────────────────────────────────────────────
  {
    id: 'b_lidocaine',
    name: 'Lidocaine',
    indication: 'Regional / Infiltration',
    concentration: [{ label: '1% (10 mg/mL)', mgPerMl: 10 }, { label: '2% (20 mg/mL)', mgPerMl: 20 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'local',
    doses: {
      standard: { min: 3.0, max: 4.5 },
    },
    maxDose: 300,
    notes: 'Barash Table 22-9: max 4.5 mg/kg plain, 7 mg/kg with epinephrine. CVS:CNS ratio = 7.1 (safest amide LA). Relative CNS toxicity potency = 1.0 (reference).',
    ref: 'Barash Clinical Anesthesia 9e, Ch.22 Tables 22-8, 22-9 pp.1703–1704',
    contraindications: [],
    color: '#64748b',
  },
  {
    id: 'b_lidocaine_epi',
    name: 'Lidocaine + Epinephrine',
    indication: 'Regional / Infiltration (with vasoconstrictor)',
    concentration: [{ label: '1% (10 mg/mL)', mgPerMl: 10 }, { label: '2% (20 mg/mL)', mgPerMl: 20 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'local',
    doses: {
      standard: { min: 5.0, max: 7.0 },
    },
    maxDose: 500,
    notes: 'Barash Table 22-9: max 7 mg/kg with epinephrine. Epinephrine delays absorption, reduces peak plasma concentration.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.22 Table 22-9 p.1705',
    contraindications: [],
    color: '#64748b',
  },
  {
    id: 'b_bupivacaine',
    name: 'Bupivacaine',
    indication: 'Regional / Peripheral Nerve Block / Spinal',
    concentration: [{ label: '0.25% (2.5 mg/mL)', mgPerMl: 2.5 }, { label: '0.5% (5 mg/mL)', mgPerMl: 5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'local',
    doses: {
      standard: { min: 1.5, max: 2.5 },
    },
    maxDose: 150,
    notes: 'Barash Table 22-9: max 2.5 mg/kg plain, 3 mg/kg with epi. MOST CARDIOTOXIC amide LA (CVS:CNS ratio = 2.0). Treat LAST with lipid emulsion 20%. ABSOLUTE contraindication for IV regional (Bier block).',
    ref: 'Barash Clinical Anesthesia 9e, Ch.22 Tables 22-8, 22-9 pp.1703–1708',
    contraindications: [],
    color: '#64748b',
    isHighAlert: true,
  },
  {
    id: 'b_ropivacaine',
    name: 'Ropivacaine',
    indication: 'Regional / Epidural / Peripheral Nerve Block',
    concentration: [{ label: '0.2% (2 mg/mL)', mgPerMl: 2 }, { label: '0.5% (5 mg/mL)', mgPerMl: 5 }, { label: '0.75% (7.5 mg/mL)', mgPerMl: 7.5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'local',
    doses: {
      standard: { min: 2.0, max: 3.0 },
    },
    maxDose: 300,
    notes: 'Barash: max 3–4 mg/kg. Pure S(−) enantiomer. 30–40% less cardiotoxic than bupivacaine (propyl vs butyl side chain). CVS:CNS ratio = 2.0. Less motor block than bupivacaine.',
    ref: 'Barash Clinical Anesthesia 9e, Ch.22 Table 22-8 pp.1703–1708',
    contraindications: [],
    color: '#64748b',
  },
];
