// Drug database — doses referenced from Miller's Anesthesia, 9th Edition
// Each drug: name, concentration(s), dose ranges, weight basis, adjustments, reference

export const CATEGORIES = [
  { id: 'induction',    label: 'Induction',       icon: '💉' },
  { id: 'benzo',        label: 'Benzodiazepines', icon: '😴' },
  { id: 'opioid',       label: 'Opioids',         icon: '🩺' },
  { id: 'ndmr',         label: 'NMB — Non-dep.',  icon: '💪' },
  { id: 'dmr',          label: 'NMB — Depol.',    icon: '⚡' },
  { id: 'reversal',     label: 'Reversal',         icon: '🔄' },
  { id: 'vasopressor',  label: 'Vasopressors',    icon: '❤️' },
  { id: 'antiemetic',   label: 'Antiemetics',     icon: '🛡️' },
  { id: 'emergency',    label: 'Emergency',       icon: '🚨' },
  { id: 'local',        label: 'Local Anesthetics',icon: '📍' },
];

// weightBasis: 'TBW' | 'IBW' | 'LBW' | 'fixed'
// unit: 'mg/kg' | 'mcg/kg' | 'mg' | 'mcg' | 'mcg/kg/min' | 'mg/kg/h'
// doses: { standard, elderly, obese, pediatric, cardiac, hepatic, renal }

export const DRUGS = [
  // ── INDUCTION ──────────────────────────────────────────────────────────
  {
    id: 'propofol_ind',
    name: 'Propofol',
    indication: 'Induction',
    concentration: [{ label: '1%', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard:  { min: 1.5, max: 2.5 },
      elderly:   { min: 1.0, max: 1.5 },
      cardiac:   { min: 0.5, max: 1.5 },
      hypo:      { min: 0.5, max: 1.0 },
    },
    notes: 'Titrate slowly. Reduce 30–50% in elderly, cardiac disease, hypovolemia.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.831",
    contraindications: [],
    color: '#6366f1',
  },
  {
    id: 'propofol_maint',
    name: 'Propofol',
    indication: 'Maintenance (TIVA)',
    concentration: [{ label: '1%', mgPerMl: 10 }],
    unit: 'mcg/kg/min',
    weightBasis: 'LBW',
    category: 'induction',
    doses: {
      standard: { min: 50, max: 150 },
      elderly:  { min: 25, max: 75 },
    },
    notes: 'Use LBW in obese patients. Target sedation with BIS 40–60.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.833",
    contraindications: [],
    color: '#6366f1',
    isInfusion: true,
  },
  {
    id: 'thiopental',
    name: 'Thiopental (Pentothal)',
    indication: 'Induction',
    concentration: [{ label: '2.5%', mgPerMl: 25 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 3.0, max: 5.0 },
      elderly:  { min: 2.0, max: 3.0 },
      hypo:     { min: 1.0, max: 2.0 },
    },
    notes: 'Contraindicated in porphyria. Reduce dose in elderly and hypovolemia.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.822",
    contraindications: ['porphyria'],
    color: '#8b5cf6',
  },
  {
    id: 'ketamine_iv',
    name: 'Ketamine',
    indication: 'Induction (IV)',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }, { label: '50 mg/mL', mgPerMl: 50 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 1.0, max: 2.0 },
      elderly:  { min: 0.5, max: 1.5 },
    },
    notes: 'Dissociative anesthetic. Maintains airway reflexes and BP. Ideal for hemodynamic instability and trauma.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.851",
    contraindications: ['raised_icp', 'ischemic_heart'],
    color: '#f59e0b',
  },
  {
    id: 'ketamine_im',
    name: 'Ketamine',
    indication: 'Induction (IM)',
    concentration: [{ label: '50 mg/mL', mgPerMl: 50 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 4.0, max: 6.0 },
    },
    notes: 'IM route for uncooperative patients or when IV access unavailable.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.851",
    contraindications: [],
    color: '#f59e0b',
  },
  {
    id: 'etomidate',
    name: 'Etomidate',
    indication: 'Induction',
    concentration: [{ label: '2 mg/mL', mgPerMl: 2 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'induction',
    doses: {
      standard: { min: 0.2, max: 0.3 },
      elderly:  { min: 0.1, max: 0.2 },
    },
    notes: 'Hemodynamically stable induction. Single dose — adrenal suppression lasts 6–8h. Avoid in sepsis or prolonged use.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.847",
    contraindications: ['adrenal_insufficiency'],
    color: '#10b981',
  },

  // ── BENZODIAZEPINES ────────────────────────────────────────────────────
  {
    id: 'midazolam_iv',
    name: 'Midazolam',
    indication: 'Premedication / Sedation (IV)',
    concentration: [{ label: '1 mg/mL', mgPerMl: 1 }, { label: '5 mg/mL', mgPerMl: 5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'benzo',
    doses: {
      standard: { min: 0.02, max: 0.08 },
      elderly:  { min: 0.01, max: 0.03 },
    },
    maxDose: 5,
    notes: 'Titrate slowly IV. Max 5 mg. Reduce 50% in elderly. Monitor for respiratory depression.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.856",
    contraindications: [],
    color: '#06b6d4',
  },
  {
    id: 'midazolam_im',
    name: 'Midazolam',
    indication: 'Premedication (IM)',
    concentration: [{ label: '5 mg/mL', mgPerMl: 5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'benzo',
    doses: {
      standard: { min: 0.05, max: 0.1 },
      elderly:  { min: 0.025, max: 0.05 },
    },
    maxDose: 10,
    notes: 'Give 30–60 min before induction. Onset 5–15 min.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.856",
    contraindications: [],
    color: '#06b6d4',
  },
  {
    id: 'diazepam',
    name: 'Diazepam',
    indication: 'Premedication / Sedation (IV)',
    concentration: [{ label: '5 mg/mL', mgPerMl: 5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'benzo',
    doses: {
      standard: { min: 0.1, max: 0.2 },
      elderly:  { min: 0.05, max: 0.1 },
    },
    maxDose: 10,
    notes: 'Long half-life. Use with caution in elderly and hepatic failure. Avoid in porphyria.',
    ref: "Miller's Anesthesia 9e, Ch.23 p.856",
    contraindications: [],
    color: '#06b6d4',
  },

  // ── OPIOIDS ────────────────────────────────────────────────────────────
  {
    id: 'fentanyl',
    name: 'Fentanyl',
    indication: 'Analgesia / Induction supplement',
    concentration: [{ label: '50 mcg/mL', mgPerMl: 0.05 }],
    unit: 'mcg/kg',
    weightBasis: 'TBW',
    category: 'opioid',
    doses: {
      standard: { min: 1.0, max: 3.0 },
      elderly:  { min: 0.5, max: 1.5 },
    },
    notes: 'High lipid solubility, rapid onset. Reduce in elderly. Context-sensitive half-life increases with infusion duration.',
    ref: "Miller's Anesthesia 9e, Ch.24 p.892",
    contraindications: [],
    color: '#ec4899',
    isMcg: true,
  },
  {
    id: 'morphine',
    name: 'Morphine',
    indication: 'Analgesia (IV)',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'opioid',
    doses: {
      standard: { min: 0.05, max: 0.1 },
      elderly:  { min: 0.02, max: 0.05 },
    },
    notes: 'Active metabolite morphine-6-glucuronide accumulates in renal failure — use with caution.',
    ref: "Miller's Anesthesia 9e, Ch.24 p.874",
    contraindications: ['renal'],
    color: '#ec4899',
  },
  {
    id: 'pethidine',
    name: 'Pethidine (Meperidine)',
    indication: 'Analgesia (IV/IM)',
    concentration: [{ label: '50 mg/mL', mgPerMl: 50 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'opioid',
    doses: {
      standard: { min: 0.5, max: 1.0 },
      elderly:  { min: 0.25, max: 0.5 },
    },
    maxDose: 100,
    notes: 'Avoid in renal failure (norpethidine accumulation → seizures). Avoid with MAOIs.',
    ref: "Miller's Anesthesia 9e, Ch.24 p.876",
    contraindications: ['renal', 'maoi'],
    color: '#ec4899',
  },
  {
    id: 'remifentanil',
    name: 'Remifentanil',
    indication: 'Infusion (intraoperative)',
    concentration: [{ label: '20 mcg/mL', mgPerMl: 0.02 }, { label: '50 mcg/mL', mgPerMl: 0.05 }],
    unit: 'mcg/kg/min',
    weightBasis: 'LBW',
    category: 'opioid',
    doses: {
      standard: { min: 0.05, max: 0.5 },
      elderly:  { min: 0.025, max: 0.25 },
    },
    notes: 'Ultra-short acting (t½ 3–5 min). Ester hydrolysis — safe in renal/hepatic failure. Plan postop analgesia before stopping.',
    ref: "Miller's Anesthesia 9e, Ch.24 p.898",
    contraindications: [],
    color: '#ec4899',
    isInfusion: true,
    isMcg: true,
  },

  // ── NMB NON-DEPOLARIZING ────────────────────────────────────────────────
  {
    id: 'rocuronium_int',
    name: 'Rocuronium',
    indication: 'Intubation (standard)',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.6, max: 0.6 },
      obese: { min: 0.6, max: 0.6 },
    },
    notes: 'Use IBW in obese. Onset 60–90s. Duration 30–60 min. Reversible by sugammadex.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.995",
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'rocuronium_rsi',
    name: 'Rocuronium',
    indication: 'RSI dose',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'ndmr',
    doses: {
      standard: { min: 1.0, max: 1.2 },
    },
    notes: 'RSI dose: onset ~60s (similar to succinylcholine). Requires sugammadex 16 mg/kg for immediate reversal.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.995",
    contraindications: [],
    color: '#34d399',
    isHighAlert: true,
  },
  {
    id: 'rocuronium_maint',
    name: 'Rocuronium',
    indication: 'Maintenance',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.1, max: 0.2 },
    },
    notes: 'Give when T1 returns to 25%. Monitor with TOF.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.995",
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'vecuronium',
    name: 'Vecuronium',
    indication: 'Intubation',
    concentration: [{ label: '1 mg/mL (reconstituted)', mgPerMl: 1 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.08, max: 0.12 },
    },
    notes: 'Avoid in hepatic failure (biliary excretion). Use with caution in renal failure.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.998",
    contraindications: ['hepatic'],
    color: '#34d399',
  },
  {
    id: 'atracurium',
    name: 'Atracurium',
    indication: 'Intubation',
    concentration: [{ label: '10 mg/mL', mgPerMl: 10 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.4, max: 0.5 },
    },
    notes: 'Hoffmann elimination — safe in renal AND hepatic failure. Histamine release at high doses.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.1000",
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'cisatracurium',
    name: 'Cisatracurium',
    indication: 'Intubation',
    concentration: [{ label: '2 mg/mL', mgPerMl: 2 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.15, max: 0.2 },
    },
    notes: 'Hoffmann elimination. No histamine release. Preferred in ICU and organ failure patients.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.1001",
    contraindications: [],
    color: '#34d399',
  },
  {
    id: 'pancuronium',
    name: 'Pancuronium',
    indication: 'Intubation (long duration)',
    concentration: [{ label: '2 mg/mL', mgPerMl: 2 }],
    unit: 'mg/kg',
    weightBasis: 'IBW',
    category: 'ndmr',
    doses: {
      standard: { min: 0.08, max: 0.1 },
    },
    notes: 'Long duration (60–90 min). Vagolytic — increases HR. Renal excretion — avoid in renal failure.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.998",
    contraindications: ['renal', 'tachycardia'],
    color: '#34d399',
  },

  // ── NMB DEPOLARIZING ───────────────────────────────────────────────────
  {
    id: 'succinylcholine',
    name: 'Succinylcholine',
    indication: 'RSI / Intubation',
    concentration: [{ label: '20 mg/mL', mgPerMl: 20 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'dmr',
    doses: {
      standard: { min: 1.0, max: 1.5 },
    },
    notes: '⚠️ CONTRAINDICATED in: denervation, burns, crush injury, prolonged immobilization, DMD, hyperkalaemia, MH history, penetrating eye injury.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.981",
    contraindications: ['denervation', 'burns', 'mh', 'hyperkalemia', 'dmd'],
    color: '#ef4444',
    isHighAlert: true,
  },

  // ── REVERSAL ───────────────────────────────────────────────────────────
  {
    id: 'neostigmine',
    name: 'Neostigmine',
    indication: 'Reversal of NDMR',
    concentration: [{ label: '0.5 mg/mL', mgPerMl: 0.5 }, { label: '2.5 mg/mL', mgPerMl: 2.5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 0.04, max: 0.07 },
    },
    maxDose: 5,
    notes: 'Must be given with atropine (0.01–0.02 mg/kg) or glycopyrrolate (0.01 mg/kg) to prevent bradycardia. Use only when TOF ≥ T2.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.1015",
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'atropine_rev',
    name: 'Atropine (with neostigmine)',
    indication: 'Anticholinergic cover for reversal',
    concentration: [{ label: '0.5 mg/mL', mgPerMl: 0.5 }, { label: '1 mg/mL', mgPerMl: 1 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 0.01, max: 0.02 },
    },
    maxDose: 1.2,
    notes: 'Give before or with neostigmine to prevent bradycardia and hypersalivation.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.1015",
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'sugammadex_mod',
    name: 'Sugammadex',
    indication: 'Reversal — moderate block (TOF T2)',
    concentration: [{ label: '100 mg/mL', mgPerMl: 100 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 2.0, max: 2.0 },
    },
    notes: 'Rocuronium / vecuronium only. Use when TOF count ≥ T2 (moderate block). Complete reversal in ~3 min.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.1017",
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'sugammadex_deep',
    name: 'Sugammadex',
    indication: 'Reversal — deep block (PTC 1–2)',
    concentration: [{ label: '100 mg/mL', mgPerMl: 100 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 4.0, max: 4.0 },
    },
    notes: 'Use when TOF count = 0 and PTC 1–2. Deep block reversal.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.1017",
    contraindications: [],
    color: '#a78bfa',
  },
  {
    id: 'sugammadex_imm',
    name: 'Sugammadex',
    indication: 'Reversal — immediate (RSI rocuronium)',
    concentration: [{ label: '100 mg/mL', mgPerMl: 100 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'reversal',
    doses: {
      standard: { min: 16.0, max: 16.0 },
    },
    notes: 'For "cannot intubate cannot oxygenate" after RSI rocuronium 1.2 mg/kg. Give within 3 min of rocuronium.',
    ref: "Miller's Anesthesia 9e, Ch.29 p.1017",
    contraindications: [],
    color: '#ef4444',
    isHighAlert: true,
  },

  // ── VASOPRESSORS ───────────────────────────────────────────────────────
  {
    id: 'ephedrine',
    name: 'Ephedrine',
    indication: 'Hypotension (IV bolus)',
    concentration: [{ label: '5 mg/mL (diluted)', mgPerMl: 5 }],
    unit: 'mg',
    weightBasis: 'fixed',
    category: 'vasopressor',
    doses: {
      standard: { min: 5, max: 10 },
    },
    notes: 'First-line for spinal-induced hypotension. Mixed α+β agonist — increases HR and BP. Prepare as 5 mg/mL.',
    ref: "Miller's Anesthesia 9e, Ch.19 p.651",
    contraindications: [],
    color: '#f97316',
  },
  {
    id: 'phenylephrine',
    name: 'Phenylephrine',
    indication: 'Hypotension (IV bolus)',
    concentration: [{ label: '100 mcg/mL (diluted)', mgPerMl: 0.1 }],
    unit: 'mcg',
    weightBasis: 'fixed',
    category: 'vasopressor',
    doses: {
      standard: { min: 50, max: 200 },
    },
    notes: 'Pure α-agonist — increases SVR without raising HR. Preferred in tachycardia. May cause reflex bradycardia.',
    ref: "Miller's Anesthesia 9e, Ch.19 p.651",
    contraindications: [],
    color: '#f97316',
    isMcg: true,
  },
  {
    id: 'norepinephrine',
    name: 'Norepinephrine',
    indication: 'Vasopressor infusion',
    concentration: [{ label: '4 mcg/mL (standard mix)', mgPerMl: 0.004 }],
    unit: 'mcg/kg/min',
    weightBasis: 'TBW',
    category: 'vasopressor',
    doses: {
      standard: { min: 0.01, max: 0.5 },
    },
    notes: 'Predominantly α-agonist with some β1. First-line vasopressor for septic shock.',
    ref: "Miller's Anesthesia 9e, Ch.19 p.649",
    contraindications: [],
    color: '#f97316',
    isInfusion: true,
    isMcg: true,
  },

  // ── ANTIEMETICS ────────────────────────────────────────────────────────
  {
    id: 'dexamethasone',
    name: 'Dexamethasone',
    indication: 'PONV prophylaxis',
    concentration: [{ label: '4 mg/mL', mgPerMl: 4 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'antiemetic',
    doses: {
      standard: { min: 0.05, max: 0.1 },
    },
    maxDose: 8,
    notes: 'Give at induction. Max 8 mg. Transient perineal burning if injected rapidly. Monitor glucose in diabetics.',
    ref: "Miller's Anesthesia 9e, Ch.89 p.2773",
    contraindications: [],
    color: '#22d3ee',
  },
  {
    id: 'ondansetron',
    name: 'Ondansetron',
    indication: 'PONV prophylaxis / treatment',
    concentration: [{ label: '2 mg/mL', mgPerMl: 2 }],
    unit: 'mg',
    weightBasis: 'fixed',
    category: 'antiemetic',
    doses: {
      standard: { min: 4, max: 8 },
    },
    notes: 'Give 30 min before end of surgery for prophylaxis. 4 mg fixed dose. Avoid in QT prolongation.',
    ref: "Miller's Anesthesia 9e, Ch.89 p.2773",
    contraindications: [],
    color: '#22d3ee',
  },

  // ── EMERGENCY ──────────────────────────────────────────────────────────
  {
    id: 'epinephrine_anaphylaxis',
    name: 'Epinephrine (Adrenaline)',
    indication: 'Anaphylaxis',
    concentration: [{ label: '1:10,000 (0.1 mg/mL)', mgPerMl: 0.1 }, { label: '1:1,000 (1 mg/mL)', mgPerMl: 1 }],
    unit: 'mcg/kg',
    weightBasis: 'TBW',
    category: 'emergency',
    doses: {
      standard: { min: 5, max: 10 },
    },
    notes: '⚠️ For anaphylaxis: 5–10 mcg/kg IV. For cardiac arrest: 1 mg IV (fixed). Use 1:10,000 for IV bolus.',
    ref: "Miller's Anesthesia 9e, Ch.40 p.1289",
    contraindications: [],
    color: '#ef4444',
    isHighAlert: true,
    isMcg: true,
  },
  {
    id: 'atropine_brady',
    name: 'Atropine',
    indication: 'Bradycardia',
    concentration: [{ label: '0.5 mg/mL', mgPerMl: 0.5 }, { label: '1 mg/mL', mgPerMl: 1 }],
    unit: 'mg',
    weightBasis: 'fixed',
    category: 'emergency',
    doses: {
      standard: { min: 0.5, max: 1.0 },
    },
    maxDose: 3.0,
    notes: 'For symptomatic bradycardia. Repeat every 3–5 min. Total max 3 mg (full vagal block).',
    ref: "Miller's Anesthesia 9e, Ch.18 p.630",
    contraindications: [],
    color: '#ef4444',
  },
  {
    id: 'epinephrine_arrest',
    name: 'Epinephrine (Adrenaline)',
    indication: 'Cardiac Arrest (CPR)',
    concentration: [{ label: '1:10,000 (0.1 mg/mL)', mgPerMl: 0.1 }],
    unit: 'mg',
    weightBasis: 'fixed',
    category: 'emergency',
    doses: {
      standard: { min: 1.0, max: 1.0 },
    },
    notes: '⚠️ 1 mg IV every 3–5 min during CPR. Use 1:10,000 (0.1 mg/mL) = 10 mL per dose.',
    ref: "Miller's Anesthesia 9e, Ch.99 p.3071",
    contraindications: [],
    color: '#ef4444',
    isHighAlert: true,
  },

  // ── LOCAL ANESTHETICS ──────────────────────────────────────────────────
  {
    id: 'bupivacaine',
    name: 'Bupivacaine',
    indication: 'Regional / Infiltration',
    concentration: [{ label: '0.25% (2.5 mg/mL)', mgPerMl: 2.5 }, { label: '0.5% (5 mg/mL)', mgPerMl: 5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'local',
    doses: {
      standard: { min: 1.5, max: 2.5 },
    },
    maxDose: 150,
    notes: 'Max dose: 2.5 mg/kg (plain), 3 mg/kg (with epinephrine). Highly cardiotoxic — use smallest effective dose.',
    ref: "Miller's Anesthesia 9e, Ch.36 p.1167",
    contraindications: [],
    color: '#64748b',
  },
  {
    id: 'ropivacaine',
    name: 'Ropivacaine',
    indication: 'Regional / Infiltration',
    concentration: [{ label: '0.2% (2 mg/mL)', mgPerMl: 2 }, { label: '0.75% (7.5 mg/mL)', mgPerMl: 7.5 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'local',
    doses: {
      standard: { min: 1.5, max: 3.0 },
    },
    maxDose: 300,
    notes: 'Less cardiotoxic than bupivacaine. Max dose 3 mg/kg (plain), 4 mg/kg (with epinephrine).',
    ref: "Miller's Anesthesia 9e, Ch.36 p.1170",
    contraindications: [],
    color: '#64748b',
  },
  {
    id: 'lidocaine',
    name: 'Lidocaine',
    indication: 'Regional / Infiltration / IV',
    concentration: [{ label: '1% (10 mg/mL)', mgPerMl: 10 }, { label: '2% (20 mg/mL)', mgPerMl: 20 }],
    unit: 'mg/kg',
    weightBasis: 'TBW',
    category: 'local',
    doses: {
      standard: { min: 3.0, max: 5.0 },
    },
    maxDose: 500,
    notes: 'Max dose: 5 mg/kg (plain), 7 mg/kg (with epinephrine). IV bolus for VT: 1–1.5 mg/kg.',
    ref: "Miller's Anesthesia 9e, Ch.36 p.1163",
    contraindications: [],
    color: '#64748b',
  },
];
